<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>JaySharp.Cli</PackageId>
    <Version>1.0.18</Version>
    <Authors>jhoney</Authors>
    <Company>SpectacledJay</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <AssemblyName>JaySharp</AssemblyName>

    <PackAsTool>true</PackAsTool>
    <ToolCommandName>JaySharp</ToolCommandName>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <ProjectReference Include="..\JaySharp.Core\JaySharp.Core.csproj" />
    <ProjectReference Include="..\..\tests\JaySharp.Tests\JaySharp.Tests.csproj" />
  </ItemGroup>

</Project>
