using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace JaySharp.Generators;

[Generator]
public class JayFeatureGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Target classes and methods with attributes
        IncrementalValuesProvider<ClassDeclarationSyntax> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax syntax && syntax.AttributeLists.Count > 0,
                transform: static (generatorContext, _) => (ClassDeclarationSyntax)generatorContext.Node)
            .Where(static declaration => declaration is not null);

        IncrementalValueProvider<ImmutableArray<ClassDeclarationSyntax>> compilation = classDeclarations.Collect();

        context.RegisterSourceOutput(compilation, static (sourceProductionContext, classDeclarations) =>
        {
            StringBuilder sourceBuilder = new();
            sourceBuilder.AppendLine("// <auto-generated/>");
            sourceBuilder.AppendLine("namespace JaySharp.Generated;");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("public static class JayFeatureRegistry");
            sourceBuilder.AppendLine("{");
            sourceBuilder.AppendLine("    public static readonly string[] DiscoveredFeatureClasses = new string[]");
            sourceBuilder.AppendLine("    {");

            foreach (ClassDeclarationSyntax classDeclaration in classDeclarations)
            {
                string className = classDeclaration.Identifier.Text;
                sourceBuilder.AppendLine($"        \"{className}\",");
            }

            sourceBuilder.AppendLine("    };");
            sourceBuilder.AppendLine("}");

            sourceProductionContext.AddSource("JayFeatureRegistry.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
        });
    }
}
